# Generated by Django 3.1.3 on 2021-02-26 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Breed')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='Sorted')),
            ],
            options={
                'verbose_name': 'breed',
                'verbose_name_plural': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='Nickname')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('f', 'Female'), ('m', 'Mail')], default='f', max_length=1, verbose_name='Sex')),
                ('is_sterilized', models.BooleanField(blank=True, default=False, verbose_name='Is sterilized')),
                ('microchip_number', models.CharField(max_length=15, null=True, verbose_name='Microchip number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dog.breed', verbose_name='Breed')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
