# Generated by Django 3.1.3 on 2021-05-11 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Dog', 'verbose_name_plural': 'Dogs'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='microchip_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Microchip number'),
        ),
        migrations.CreateModel(
            name='DogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'Walk'), ('u', 'User action')], max_length=1)),
                ('start_action', models.DateTimeField(verbose_name='Start action')),
                ('end_action', models.DateTimeField(blank=True, null=True, verbose_name='End action')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.dog', verbose_name='Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
